SELECT 
    GETDATE() current_date_time;

SELECT 
    CONVERT(DATE, GETDATE()) [Current Date];

SELECT 
    TRY_CONVERT(DATE, GETDATE()),
    CAST(GETDATE() AS DATE);

SELECT 
    CONVERT(TIME,GETDATE()),
    TRY_CONVERT(TIME, GETDATE()),
    CAST(GETDATE() AS TIME);